### ISSUE TITLE
problem with the latest update

### ISSUE THREAD

**Issue by x-Tera-x** [jesus-figueroa/lol-account-checker#10]
i keep getting this message when the account is not in NA or EUW region which is : 
Traceback (most recent call last):
  File "C:\Users\Ahmed\Desktop\League crack accounts\lol-account-checker-main\lol-account-checker-main\test.py", line 354, in <module>
    account_checker = AccountChecker(username, password)
  File "C:\Users\Ahmed\Desktop\League crack accounts\lol-account-checker-main\lol-account-checker-main\test.py", line 163, in __init__
    self.purchase_history = self.get_purchase_history()
  File "C:\Users\Ahmed\Desktop\League crack accounts\lol-account-checker-main\lol-account-checker-main\test.py", line 239, in get_purchase_history
    response = self.session.get(Constants.HISTORY_URL.format(region_tag=self.region_tag)).json()
  File "C:\Users\Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='las.store.leagueoflegends.com', port=443): Max retries exceeded with url: /storefront/v3/history/purchase (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001D9F1EB46D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by jesus-figueroa** [comment]
Should be working now.
