### ISSUE TITLE
error nonetype

### ISSUE THREAD

**Issue by H3XBAE** [jesus-figueroa/lol-account-checker#19]
Error occured while checking account
Traceback (most recent call last):
  File "\lolchecker.py", line 446, in <module>
    account_checker = AccountChecker(username, password)
  File "\lolchecker.py", line 202, in __init__
    self.region_id = self.user_info["region"]["id"]
TypeError: 'NoneType' object is not subscriptable

while deleting the file also procced with same error on the next 2 lines.

**Comment by ErickDDO** [comment]
Updating... It doesn't work anymore!
