### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by kbrav0** [jesus-figueroa/lol-account-checker#20]
When i try to run the program i get the following error message

Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:\Users\username\Desktop\SPOOOOF\checkers de lol\lol-account-checker-main\lolchecker.py
Checking/building champion data...
Traceback (most recent call last):
  File "C:\Users\username\Desktop\SPOOOOF\checkers de lol\lol-account-checker-main\lolchecker.py", line 428, in <module>
    cache_champion_data.get_champion_data()
  File "C:\Users\username\Desktop\SPOOOOF\checkers de lol\lol-account-checker-main\lolchecker.py", line 165, in get_champion_data
    champion_data = json.load(reader)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\username\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Don't know what to do followed the pip install requests step.

**Comment by nullcst** [comment]
did you rename your checker.env.example file to checker.env?

**Comment by ErickDDO** [comment]
I have the same problem as fellow **kbrav0**, here it is giving the same message and it is not working.

**Comment by ErickDDO** [comment]
> did you rename your checker.env.example file to checker.env?

Yes nullcst, I also changed the file to checker.env, even so the error continues, is yours working?

![error](https://user-images.githubusercontent.com/94616401/172994240-fc484082-0a25-4cc3-a870-5d26373a3e9e.png)

**Comment by steele123** [comment]
Seems to be an issue related to riot, seems there must be a new different way to authenticate and get a token and this one isn't working.

**Comment by ErickDDO** [comment]
> Seems to be an issue related to riot, seems there must be a new different way to authenticate and get a token and this one isn't working.

Really steele123, it must be Riot itself.

**Comment by ErickDDO** [comment]
Updating... It doesn't work anymore!
