### ISSUE TITLE
Missing Output

### ISSUE THREAD

**Issue by Dallair220** [jesus-figueroa/lol-account-checker#22]
The console sent this here: _Complete! Account information located in accounts-2022-08-30_11-17-34.txt_
But when checking the "output" folder inside "lol-account-checker-main", it's empty.

Furthermore, there seemed to be an error. 
Below, you can see an excerpt of the console output:

> Checking accounts, please wait...
> Error occured while checking nyywkm36777
> Traceback (most recent call last):
>   File "C:\Users\Paul\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "C:\Users\Paul\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "C:\Users\Paul\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Users\Paul\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Paul\Desktop\Misc\4) Python\lol-account-checker-main\lolchecker.py", line 446, in <module>
>     account_checker = AccountChecker(username, password)
>   File "C:\Users\Paul\Desktop\Misc\4) Python\lol-account-checker-main\lolchecker.py", line 187, in __init__
>     tokens = self._authorize()
>   File "C:\Users\Paul\Desktop\Misc\4) Python\lol-account-checker-main\lolchecker.py", line 234, in _authorize
>     ).json()
>   File "C:\Users\Paul\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 917, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: [Errno Expecting value] <!DOCTYPE html>
> <html lang="en-US">
> <head>
> <title>Access denied</title>

How can I fix this?
Thanks for having a look into it.

**Comment by ErickDDO** [comment]
NO LONGER WORKING!
